version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: src/AnotherWeatherForecast.Api/Dockerfile
    ports:
      - "5000:8080"
    # add restart policy to ensure the container restarts on failure for docker swarm
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      WeatherSources__OpenMeteo__Enabled: "true"
      WeatherSources__WeatherApi__Enabled: "true"
      WeatherSources__OpenWeatherMap__Enabled: "true"
      WeatherSources__WeatherApi__ApiKey: "${WEATHERAPI_KEY}"
      WeatherSources__OpenWeatherMap__ApiKey: "${OPENWEATHERMAP_KEY}"
      OpenTelemetry__OtlpEndpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
      OpenTelemetry__OtlpHeaders: "${OTEL_EXPORTER_OTLP_HEADERS}"